### ISSUE TITLE
Updated CMake

### ISSUE THREAD

**Issue by pr0g** [wahez/cpp_on_sea_exercises#1]
Hey David and Walther,

I've added a new folder to the code/ directory called updated_cmake - it contains an updated cmake script and a README with a cross platform version that should make building and running the examples in future a bit easier. Let me know if I missed anything or got anything wrong!

Please feel free to close out the issue once you've had a look at it the added stuff,

Thanks!

Tom

**Comment by pr0g** [comment]
I've tested this on macOS now too and everything works as it does on Windows. It'd be cool to hear if it works on Linux too, thanks! 😄

**Comment by david-grs** [comment]
Hey, Thanks a lot for the fix - much appreciated!

Cheers
David

**Comment by pr0g** [comment]
No worries! :)

The same changes should be able to be applied to the other examples (the only change is going to be the .cc file I think) though potentially the papi lib will need to be conditionally included based on the platform as I do not believe it's supported on Windows.

The changes should hopefully make using benchmark easier and all .cc files just need to #include "benchmark/benchmark.h"

Thanks again for the great training! I don't suppose you could share the code from the std::accumulate example with the boost usage code? That was really interesting to see during the session.

Thanks again!


Tom

**Comment by pr0g** [comment]
I realized a couple of things I might have missed in my README - when building benchmark on *nix/macOS, when first running CMake I think you do need to provide the build type... so this:

```
cmake .. -DCMAKE_BUILD_TYPE=RELEASE
```

Otherwise you might see the warning while running that you've built in Debug.

And also to use the `$<IF:...,...,...>` CMake generator expression you'll need CMake >= 3.8 - I think I set it to 2.8.12, so you may need to bump that, or switch back to using more old school `if(MSVC)… else()` blocks.

Thanks!
